#curl -u ala:ala123 localhost:8080/me           # ROLE_ADMINS + ROLE_DEVELOPERS
#curl -u ala:ala123 localhost:8080/admin/panel  # 200
#curl -u jan:jan123 localhost:8080/admin/panel  # 403
#curl localhost:8080/public                     # 200
#
## po stronie LDAP
#docker compose exec openldap ldapsearch -x -H ldap://localhost \
#  -D cn=admin,dc=example,dc=org -w admin -b dc=example,dc=org "(uid=jan)"