POST http://localhost:8080/api/cards
Accept: application/json
Content-Type: application/json
Authorization: Basic amFuOjEyMw==
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo4MDAwIiwidXNlciI6ImphbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiZXhwIjoxNzYyNTE2NjMwfQ.Uo9Ipi-D3a0DhaKexJyGeLxMno_aFFIh787goUrx6KM

{
  "currencyCode": "PLN"
}

> {%
    client.global.set('number', response.body.number);
%}

###
POST http://localhost:8080/api/cards/{{number}}/transactions
Accept: application/json
Content-Type: application/json
Authorization: Basic amFuOjEyMw==

{
  "type": "IN",
  "amount": 100,
  "currencyCode": "PLN"
}

###
POST http://localhost:8080/api/cards/{{number}}/transactions
Accept: application/json
Content-Type: application/json
Authorization: Basic amFuOjEyMw==

{
  "type": "OUT",
  "amount": 100.0,
  "currencyCode": "PLN"
}

###
GET http://localhost:8080/api/cards?pageSize=3
Accept: application/json
Content-Type: application/json
Authorization: Basic amFuOjEyMw==

###
GET http://localhost:8080/api/cards/{{number}}
Accept: application/json
Content-Type: application/json
Authorization: Basic amFuOjEyMw==

###
GET http://localhost:8080/api/users/me
Accept: application/json
Content-Type: application/json
#Authorization: Basic amFuOjEyMw==
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo4MDAwIiwidXNlciI6ImphbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiZXhwIjoxNzYyNTE2NjMwfQ.Uo9Ipi-D3a0DhaKexJyGeLxMno_aFFIh787goUrx6KM
