POST http://localhost:8080/api/cards
Accept: application/json
Content-Type: application/json
Authorization: Basic amFuOjEyMw==

{
  "currencyCode": "PLN"
}

> {%
    client.global.set('number', response.body.number);
%}

###
POST http://localhost:8080/api/cards/{{number}}/transactions
Accept: application/json
Content-Type: application/json

{
  "type": "IN",
  "amount": 20000,
  "currencyCode": "PLN"
}

###
POST http://localhost:8080/api/cards/{{number}}/transactions
Accept: application/json
Content-Type: application/json

{
  "type": "OUT",
  "amount": 100.0,
  "currencyCode": "PLN"
}

###
GET http://localhost:8080/api/cards?pageSize=3
Accept: application/json
Content-Type: application/json
#Authorization: Basic amFuOjEyMw==
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo4MDAwIiwidXNlciI6ImphbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiZXhwIjoxNzY3OTU3ODE4fQ.lRbR7h9CmuR-w3LxnSYxDG44BGmtgnaT-f5M1SiC_Kk
Authorization: API_KEY 00001

###
GET http://localhost:8080/api/cards/{{number}}
Accept: application/json
Content-Type: application/json

###
GET http://localhost:8080/api/users/me
Accept: application/json
Content-Type: application/json
Authorization: Basic amFuOjEyMw==

###

//@no-redirect
//@no-cookie-jar
POST http://localhost:8100/realms/training/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=training-client&grant_type=password&username=jan&password=123

> {%
    client.global.set('token', response.body.access_token);
    client.global.set('refreshToken', response.body.refresh_token);
%}

###

//@no-redirect
//@no-cookie-jar
POST http://localhost:8100/realms/training/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=training-client&grant_type=refresh_token&refresh_token={{ refreshToken }}

> {%
    client.global.set('token', response.body.access_token);
    client.global.set('refreshToken', response.body.refresh_token);
%}
