spring:
  application:
    name: cards
  jpa:
    generate-ddl: true
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/payments
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 6
logging:
  level:
    org.springframework: info
card-number-length: 16