spring:
  application:
    name: cards
  datasource:
    url: jdbc:postgresql://localhost:5432/payments
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 6
  jpa:
    generate-ddl: true
#    hibernate:
#      ddl-auto: create-drop
  mongodb:
    username: admin
    password: admin
    database: payments
    authentication-database: admin
    # host: localhost
    # port: 27017
  messages:
    basename: exceptions
#  main:
#    allow-circular-references: true
#  security:
#    user:
#      name: user
#      password: 123
#      roles: ADMIN
#  profiles:
#    active: dev

logging:
  level:
    org.springframework: info
card-number-length: 16
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
secret: sdfewrtfnmuiretynui